// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mizan.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mizan.Infrastructure.Migrations
{
    [DbContext(typeof(MizanDbContext))]
    partial class MizanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20").HasAnnotation("Relational:MaxIdentifierLength", 63);
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mizan.Infrastructure.Persistence.AccountRecord", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<long>("OpeningBalanceMinorUnits").HasColumnType("bigint");
                b.Property<int>("Type").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("Name", "Currency");
                b.ToTable("accounts", (string)null);
            });

            modelBuilder.Entity("Mizan.Infrastructure.Persistence.OperationRecord", b =>
            {
                b.HasOne("Mizan.Infrastructure.Persistence.OperationRecord", null).WithMany().HasForeignKey("OriginalOperationId").OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("Mizan.Infrastructure.Persistence.EffectRecord", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("AccountId").HasColumnType("uuid");
                b.Property<long>("AmountMinorUnits").HasColumnType("bigint");
                b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)");
                b.Property<int>("Direction").HasColumnType("integer");
                b.Property<DateTimeOffset>("EffectiveAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("OperationId").HasColumnType("uuid");
                b.Property<long>("Order").HasColumnType("bigint");
                b.Property<DateTimeOffset>("RecordedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("OperationId");
                b.HasIndex("AccountId", "EffectiveAt", "RecordedAt", "Order", "Id");
                b.ToTable("financial_effects", (string)null);
            });

            modelBuilder.Entity("Mizan.Infrastructure.Persistence.IdempotencyRecord", b =>
            {
                b.Property<string>("Key").HasMaxLength(200).HasColumnType("character varying(200)").UseCollation("C");
                b.Property<Guid>("OperationId").HasColumnType("uuid");
                b.HasKey("Key");
                b.HasIndex("OperationId").IsUnique();
                b.ToTable("idempotency_keys", (string)null);
            });

            modelBuilder.Entity("Mizan.Infrastructure.Persistence.OperationRecord", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTimeOffset>("EffectiveAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("OriginalOperationId").HasColumnType("uuid");
                b.Property<DateTimeOffset>("RecordedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("Type").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("OriginalOperationId").IsUnique().HasFilter("\"OriginalOperationId\" IS NOT NULL");
                b.ToTable("financial_operations", (string)null);
            });

            modelBuilder.Entity("Mizan.Infrastructure.Persistence.EffectRecord", b =>
            {
                b.HasOne("Mizan.Infrastructure.Persistence.AccountRecord", null).WithMany().HasForeignKey("AccountId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("Mizan.Infrastructure.Persistence.OperationRecord", null).WithMany().HasForeignKey("OperationId").OnDelete(DeleteBehavior.Restrict).IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}